---
abstract: 'Temporary Databases for Testing'
author:
  - 'Al Newkirk <awncorp@cpan.org>'
build_requires:
  DBI: '1.643'
  Data::Object::Class: '2.02'
  Data::Object::ClassHas: '2.01'
  Data::Object::Role::Buildable: '0.03'
  Data::Object::Role::Immutable: '2.01'
  Data::Object::Role::Stashable: '2.01'
  Test::Auto: '0.12'
  perl: '5.014'
  routines: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.015, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-DB
requires:
  DBI: '1.643'
  Data::Object::Class: '2.02'
  Data::Object::ClassHas: '2.01'
  Data::Object::Role::Buildable: '0.03'
  Data::Object::Role::Immutable: '2.01'
  Data::Object::Role::Stashable: '2.01'
  perl: '5.014'
  routines: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/iamalnewkirk/test-db/issues
  homepage: https://metacpan.org/release/AWNCORP/Test-DB-0.03
  repository: git://github.com/iamalnewkirk/test-db.git
version: '0.04'
x_authority: cpan:AWNCORP
x_generated_by_perl: v5.32.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
